#!/bin/sh

clean_sxhkd() {
  pkill sxhkd || true
  pkill sxhkd-statusd || true
  rm /tmp/sxhkd.fifo || true
  rm /tmp/sxhkd.fifo.sxhkd-statusd || true
}

clean_sxhkd
mkfifo /tmp/sxhkd.fifo
sxhkd -s /tmp/sxhkd.fifo &
sxhkd-statusd /tmp/sxhkd.fifo &

$HOME/.config/polybar/launch.sh
feh --bg-fill $HOME/Pictures/samurai-champloo-img.jpg
dunst &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Yad state=floating
# bspc rule -a tabbed border=on

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
