#!/usr/bin/env bash

# function _resize () {
#   local direction="$1"
#   local dx="$2"
#   local dy="$3"
#   bspc node -z "$direction" "$dx" "$dy"
#   xdotool key --clearmodifiers super+r
# }

# case "$1$2" in
#   "h") _resize left -20 0;;
#   "j") _resize botton 0 20;;
#   "k") _resize top 0 -20;;
#   "l") _resize right 20 0;;
#   "Sh") _resize right -20 0;;
#   "Sj") _resize top 0 20;;
#   "Sk") _resize bottom 0 -20;;
#   "Sl") _resize left 20 0;;
# esac

case "$1$2" in
  "h") bspc node -z left -20 0;;
  "j") bspc node -z bottom 0 20;;
  "k") bspc node -z top 0 -20;;
  "l") bspc node -z right 20 0;;
  "Sh") bspc node -z right -20 0;;
  "Sj") bspc node -z top 0 20;;
  "Sk") bspc node -z bottom 0 -20;;
  "Sl") bspc node -z left 20 0;;
esac

xdotool key --clearmodifiers alt+i

# bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

# bspc node -f "$1" && exit 0
# bspc query -T -d | jq -er '.layout == "tiled"' > /dev/null && exit 1
# bspc node -f "$2"
