#!/usr/bin/env bash
set -eou pipefail

ALL_WORKSPACES=$(i3-msg -t get_tree)

get_workspace_icon() {
  local workspace_number="$1"
  local application_type=$($HOME/.config/eww/scripts/i3-workspace-applications.clj "$ALL_WORKSPACES" "$workspace_number")

  case $application_type in
    Firefox)
      echo "$workspace_number "
      ;;
    kitty)
      echo "$workspace_number "
      ;;
    Spotify)
      echo "$workspace_number "
      ;;
    Chromium-browser)
      echo "$workspace_number "
      ;;

    *)
      echo "$workspace_number"
      ;;
  esac
}

WORKSPACES=($(i3-msg -t get_workspaces \
  | jq --raw-output --compact-output \
  'map([.num, .focused, .urgent]) | map(join(",")) | .[]'))

S_EXP='(box :class "workspaces"
            :orientation "h"
            :space-evenly true
            :halign "start"
            :spacing 10 '

for workspace in "${WORKSPACES[@]}"; do
  number=$(echo $workspace | awk -F, '{ printf $1 }')
  active=$(echo $workspace | awk -F, '{ printf $2 }')
  urgent=$(echo $workspace | awk -F, '{ printf $3 }')
  if [[ "$active" == "true" ]]; then
    class="active"
  else
    class="inactive"
  fi

  if [[ "$urgent" == "true" ]]; then
    class="$class urgent"
  fi

  icon=$(get_workspace_icon "$number")

  button="(button :onclick \"\$HOME/.config/i3/go-to-workspace.sh $number\"
                  :class \"$class\"
                  :timeout \"1s\" "
  button="$button \"$icon\")"

  S_EXP="$S_EXP $button"
done

S_EXP="$S_EXP)"
echo $S_EXP
