#!/usr/bin/env bash

RUNNING=$(pgrep spotify)

if [[ -n "$RUNNING" ]]; then
  STATUS=$(dbus-send --print-reply --dest=org.mpris.MediaPlayer2.spotify /org/mpris/MediaPlayer2 org.freedesktop.DBus.Properties.Get string:'org.mpris.MediaPlayer2.Player' string:'PlaybackStatus' | grep -E 'variant[ ]+string' | cut -d "\"" -f2)

  if [[ "$STATUS" == "Paused" ]]; then
    echo "paused"
  else
    echo "playing"
  fi
fi
